# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Golden' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

  # Pods for Golden

  target 'GoldenTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GoldenUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'ForecastIO'

  post_install do |installer|
      `find Pods -regex 'Pods/pop.*\\.h' -print0 | xargs -0 sed -i '' 's/\\(<\\)pop\\/\\(.*\\)\\(>\\)/\\"\\2\\"/'`
  end
end

